### ISSUE TITLE
About ddpm--------------No module named 'ddpm.discriminator'、generative et.al.

### ISSUE THREAD

**Issue by zfw-cv** [NoaCahan/X-ray2CTPA#2]
![image](https://github.com/user-attachments/assets/fa20a1a6-03d8-4e85-9d0b-816e043ae096)
Dear author, when I run the code according to your prompts, I encounter the following problem:
Traceback (most recent call last):
File "train_ddpm.py", line 2, in <module>
from ddpm.diffusion import Unet3D,GaussianDiffusion, Trainer
File "/home/***/Desktop/projects/3d_medical/X-ray2CTPA-main/ddpm/__init__.py", line 1, in <module>
from ddpm.diffusion import Unet3D, GaussianDiffusion, Trainer
File "/home/***/Desktop/projects/3d_medical/X-ray2CTPA-main/ddpm/diffusion.py", line 38, in <module>
from ddpm.discriminator import Discriminator, ones_target, zeros_target
ModuleNotFoundError: No module named 'ddpm.discriminator'
Then locate the place in the picture. However, I found that ddpm does not seem to have a discriminator and generative. I would like to ask how to solve this problem? Thank you

**Comment by zfw-cv** [comment]
I have solved it. The generative could be found in : https://github.com/Project-MONAI/GenerativeModels/tree/main
And you should pip install monai package.

**Comment by NoaCahan** [comment]
Exactly. Thanks I'll update the requirements.txt file
